collect/urls.py
from django.urls import path, include
from .views import *

app_name = "collect"

urlpatterns = [
    path('collectRequest/<int:pk>', collectRequestDetailView.as_view(), name='collectRequest_detail'),
    path('collectRequest/', collectRequest.as_view(), name='request_list'),
    path('followList/', followsListView.as_view(), name='list'),
    #path('summary/', summary.as_view(), name='summary'),
    path('api/new_colect_order/', NewCollectOrderAPI.as_view()),
    ]

dataEntry/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import *

app_name = "dataEntry"

urlpatterns = [
    path('', clientListView.as_view(), name=''),
    path('clientList/', clientListView.as_view(), name='list'),
    path('create/', clientCreateView.as_view(), name='create'),
    path('create2/<int:pk>', contractCreateView.as_view(), name='create_contract'),
    # edit or update views
    path('update/<int:pk>/', clientUpdateView.as_view(), name='update'),
    path('updateContract/<int:pk>/', contractUpdateView.as_view(), name='update_contract'),
    # path('profile/', profile, name='customProfile')
    ]

hr/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import *

app_name = "hr"

urlpatterns = [
    # path('logout/', logout, name='customLogout'),
    # path('login/', login, name='customLogin'),
    # path('profile/', profile, name='customProfile')
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('cAccounts/', include('cAccounts.urls')),
    path('track/', include('track.urls')),
    path('hr/', include('hr.urls')),
    path('clientManager/', include('clientManager.urls')),
    path('dataEntry/', include('dataEntry.urls')),
    path('DataEntry/', include('dataEntry.urls')),
    path('collect/', include('collect.urls')),
    
    
]

collect/models.py
from django.db import models
from track.models import TimeStampMixin
from clientManager.models import *
from hr.models import Employee

# Create your models here.
class CollectRequest(TimeStampMixin,models.Model):
    name            = models.CharField(max_length=100,null=True, blank=True, verbose_name="تحصيل شهر ")
    clientt         = models.ManyToManyField(Client, related_name="collect_request_clients",verbose_name="متابعات التحصيل") 
    collector       = models.ForeignKey(Employee,  on_delete=models.CASCADE ,verbose_name="المحصل")
    daftrSerial     = models.CharField(max_length=14,null=True, blank=True, verbose_name="سريال دفتر التحصيل")
    startDate       = models.DateTimeField(null=True, blank=True, verbose_name="تاريخ بدء التحصيل")
    confirmed       = models.BooleanField(null=True, default=False)

    def save(self, *args, **kwargs):
        if self.startDate:
            # Extract the month from startDate
            month = self.startDate.strftime('%m')
            # Update the name field with the month
            self.name = f"تحصيل شهر {month}"
        super().save(*args, **kwargs)

    def __str__(self):
        if self.name :
            return self.name 
        else:
            return f"تحصيل بتاريخ {self.startDate}"

collect/forms.py
from django import forms
from .models import *
from clientManager.models import Client

class CollectRequestForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CollectRequestForm, self).__init__(*args, **kwargs)
        self.fields['clientt'].queryset =   Client.objects.all().order_by('name')

    class Meta:
        model   =   CollectRequest
        fields  =   '__all__'

collect/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from clientManager.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q, Prefetch
from django.shortcuts import render, redirect
from django.views.generic import ListView, UpdateView, CreateView, DetailView
from clientManager.models import *
from datetime import date, datetime
from track.views import addTrack
from django.contrib.auth.mixins import LoginRequiredMixin
import sys
from .forms import *
from rest_framework.views import APIView
from rest_framework.response import Response
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
import json
from django.db import transaction


class collectRequestDetailView(LoginRequiredMixin, DetailView):
    model               =   CollectRequest
    template_name       =   'collect/collectRequest_detail.html'
    context_object_name =   'request'

    def get_context_data(self, **kwargs):
        context             = super().get_context_data(**kwargs)
        collectRequest_id   =   self.kwargs.get('pk')
        clients             = CollectRequest.objects.get(pk=collectRequest_id).clientt.all()
        follows             = []
        total_sum           = 0
        for cl in clients:
            follow = FollowContractServices.objects.get(clientt=cl)
            follows.append(follow)
            total_sum += follow.deservedAmount

        context['follows'] = follows
        context['total_count'] = len(follows)
        context['total_sum'] = total_sum

        return context

class collectRequest(LoginRequiredMixin, ListView):
    queryset            =   CollectRequest
    template_name       =   'collect/collectRequest_list.html'
    context_object_name =   'requests'

    # tracking
    def get(self, request, *args, **kwargs):
        # Extract user information from the request
        if request.session['group'] == "dataEntry_admin":
            depart = "مسئول ادخال بيانات"
        elif request.session['group'] == "admin_all":
            depart = "مطور أو مسئول عام"
        elif request.session['group'] == "tahseal_admin":
            depart  =   "مسئول التحصيل"

        person = request.user.first_name + " " + request.user.last_name
        details = "عرض  سجل متابعة طلبات التحصيل"
        addTrack(depart, person, details)
        return super().get(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_term = self.request.GET.get('search', '')

        if search_term:
            pass
        else:
            requests = CollectRequest.objects.all()
        context['requests'] = requests
        context['total_count'] = requests.count()  # Use 'total_count' instead of 'totalCount'

        return context

@method_decorator(csrf_exempt, name='dispatch')
class NewCollectOrderAPI(ListView):
    def post(self, request):
        data = json.loads(request.body.decode('utf-8'))
        selected_clients = data.get('clients', [])
        print(f"selected_clients => {type(selected_clients)}")
        serial = data.get('serial')
        start_collect_date = data.get('startCollectDate')
        collector_id = data.get('collectorId')

        # Validate data (add necessary validation based on your requirements)
        # ...

        # Create CollectOrder and update related objects
        with transaction.atomic():
            collect_request = CollectRequest.objects.create(
                daftrSerial=serial,
                startDate=start_collect_date,
                collector=Employee.objects.get(pk=collector_id),
            )
            selected_clients_chunks = [selected_clients[i:i+100] for i in range(0, len(selected_clients), 100)]
            for chunk in selected_clients_chunks:
                # Assuming selected_clients are client IDs
                clients = Client.objects.filter(pk__in=chunk)
                collect_request.clientt.add(*clients)

        # Handle success response
        response_content = "Collect order created successfully"
        response = HttpResponse(response_content, content_type='text/plain')
        return response



class followsListView(LoginRequiredMixin, ListView):
    queryset = FollowContractServices.objects.all()
    model = FollowContractServices
    template_name = 'collect/follow_list.html'
    context_object_name = 'follows'
    # tracking
    def get(self, request, *args, **kwargs):
        # Extract user information from the request
        if request.session['group'] == "dataEntry_admin":
            depart = "مسئول ادخال بيانات"
        elif request.session['group'] == "admin_all":
            depart = "مطور أو مسئول عام"
        elif request.session['group'] == "tahseal_admin":
            depart  =   "مسئول التحصيل"

        person = request.user.first_name + " " + request.user.last_name
        details = "عرض قائمة سجل متابعة التعاقدات"
        addTrack(depart, person, details)
        return super().get(request, *args, **kwargs)
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_term = self.request.GET.get('search', '')

        if search_term:
            follows = FollowContractServices.objects.filter(
                Q(clientt__name__icontains=search_term) |
                Q(clientt__serial__icontains=search_term) |
                Q(clientt__place__name__icontains=search_term)
            ).order_by('-created_at')
        else:
            follows = FollowContractServices.objects.all()
        context['collectors'] = Employee.objects.all()
        context['follows'] = follows.order_by('clientt__name')
        context['total_count'] = follows.count()  # Use 'total_count' instead of 'totalCount'

        return context

collect/templates/collect/client_list.html
{% extends "collect/index.html" %}    
{% load static %}

{% block title %}
    <title>سجل العملاء</title>
{% endblock %}

{% block style %}
    <!-- Your styles go here -->
{% endblock %}

{% block content %}
<div class="container-fluid">
    
    <div class="row">
        <div class="col-10 m-auto">
            <form method="get">
                <div class="input-group mb-3">
                    <input type="text" name="search" class="form-control" placeholder="ابحث بالاسم او السريال او المنطقة" aria-label="Recipient's Name" aria-describedby="button-addon2">
                    <button class="btn btn-primary" type="submit">ابحث</button>
                </div>
            </form>
            <p class="bg-light p-1 m-1 h6">
                عدد العملاء : <span class="d-inline-block text-primary">{{total_count}}</span>
            </p>
            <table class="table table-bordered table-sm text-center table-hover table-striped">
                <thead>
                    <tr>
                        <th>السريال</th>
                        <th>الاسم</th>
                        <th>المنطقة</th>
                        <th>طلب تعديل البيانات</th>
                        <th>تاريخ التحصيل التالى<th>
                    </tr>
                </thead>
                <tbody>
                    {% for client in clients %}
                        <tr>
                            <td>{{ client.serial }}</td>
                            <td>{{ client.name }}</td>
                            <td>{{ client.place.name }}</td>
                            <td>
                                <a class="btn btn-info" href="{% url 'dataEntry:update' pk=client.id %}">طلب تعديل البيانات أو التعاقد</a>
                            </td>
                            <td>
                                تاريخ التحصيل التالى
                            </td>
                        </tr>

                    {% empty %}
                        <li>No client found.</li>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

collect/templates/collect/collectRequest_detail.html
{% extends "collect/index.html" %}    
{% load static %}

{% block title %}
    <title>تفاصيل طلب التحصيل</title>
{% endblock %}

{% block style %}
    .table-bordered td{
        vertical-align:middle !important;
    }
{% endblock %}

{% block content %}
<div class="container-fluid">
    
    <div class="row">
        <div class="col-10 m-auto">
            <form method="get">
                <div class="input-group mb-3">
                    <input type="text" name="search" class="form-control" placeholder="ابحث بإسم المحصل أو اسم التحصيل أو سريال الدفتر" aria-label="Recipient's Name" aria-describedby="button-addon2">
                    <button class="btn btn-primary" type="submit">ابحث</button>
                </div>
            </form>
            <p class="bg-light text-right d-inline-block p-3 m-1 h6">
                عدد العملاء : <span class="text-primary">{{total_count}}</span>
            </p>
            <p class="bg-light text-right d-inline-block p-3 m-1 h6">
                إجمالى مبلغ التحصيل : <span class="text-danger">{{total_sum}} جنيه</span>
            </p>
            
        </div>
        <div class="col-10"  style="position: fixed; top: 10rem; display: inline-block; left: 0rem; z-index:2; overflow:scroll; height:67vh">
            <button class="btn btn-danger w-50 m-3">تأكيد نهائى</button>
            <table class="table table-bordered table-sm text-center table-hover table-striped" >
                <thead>
                    <tr>
                        <th>العميل</th>
                        <th>الخدمة</th>
                        <th>تاريخ التحصيل المفترض</th>
                        <th>مبلغ التحصيل</th>
                        <th>أمر 1</th>
                        <th>أمر 2</th>
                    </tr>
                </thead>
                <tbody>
                    {% for follow in follows %}
                        
                        <tr>
                            <td>{{follow.clientt.name}}</td>
                            <td>{{follow.contractt.servicee.name}}</td>
                            <td>{{follow.ecd|date:'Y-m-d'}}</td>
                            <td>{{follow.contractt.servicee.price}}</td>
                            <td><a class="btn btn-success" href="#">تأكيد التحصيل</a></td>
                            <td><a class="btn btn-secondary text-white">اختيارات وأوامر إخرى</a></td>
                        </tr>

                    {% empty %}
                        <li>No client found.</li>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<input type="hidden" value="{{csrf_token}}" id="csrf_token">
{% endblock %}

{% block script %}
{% endblock %}

collect/templates/collect/collectRequest_list.html
{% extends "collect/index.html" %}    
{% load static %}

{% block title %}
    <title>سجل متابعة طلبات التحصيل</title>
{% endblock %}

{% block style %}
    .table-bordered td{
        vertical-align:middle !important;
    }
{% endblock %}

{% block content %}
<div class="container-fluid">
    
    <div class="row">
        <div class="col-10 m-auto">
            <form method="get">
                <div class="input-group mb-3">
                    <input type="text" name="search" class="form-control" placeholder="ابحث بإسم المحصل أو اسم التحصيل أو سريال الدفتر" aria-label="Recipient's Name" aria-describedby="button-addon2">
                    <button class="btn btn-primary" type="submit">ابحث</button>
                </div>
            </form>
            <p class="bg-light text-right d-inline-block p-3 m-1 h6">
                عدد طلبات التحصيل : <span class="text-primary">{{total_count}}</span>
            </p>
        </div>
        <div class="col-10"  style="position: fixed; top: 16rem; display: inline-block; left: 0rem; z-index:2; overflow:scroll; height:67vh">
            <table class="table table-bordered table-sm text-center table-hover table-striped" >
                <thead>
                    <tr>
                        <th>id</th>
                        <th>اسم التحصيل</th>
                        <th>اسم المحصل</th>
                        <th>سريال دفتر التحصيل</th>
                        <th>تاريخ بدء التحصيل</th>
                        <th>تم تأكيد التحصيل</th>
                        <th>التفاصيل</th>
                    </tr>
                </thead>
                <tbody>
                    {% for request in requests %}
                        
                        <tr {% if request.confirmed %}  class="h6 bg-success text-white" {% else %} class="h6 bg-danger text-white" {%endif%}>
                            <td>{{ request.id }}</td>
                            <td>{{ request.name }}</td>
                            <td>{{ request.collector.name }}</td>
                            <td>{{ request.daftrSerial }}</td>
                            <td>{{ request.startDate |date:'Y/m/d'}}</td>
                            <td>
                            {% if request.confirmed %} تم تأكيد التحصيل {% else %} لم يتم التأكيد {%endif%}
                            </td>
                            <td class="bg-white">
                                <a class="btn btn-info w-100" href="{% url 'collect:collectRequest_detail' request.id %}">تفاصيل طلب التحصيل</a>
                            </td>
                        </tr>

                    {% empty %}
                        <li>No client found.</li>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<input type="hidden" value="{{csrf_token}}" id="csrf_token">
{% endblock %}

{% block script %}
{% endblock %}

collect/templates/collect/collect_order_form.html
{% extends "collect/index.html" %}
{% load crispy_forms_tags %}

{% block title %}
    <title>اضافة / تعديل سجل تحصيل</title>
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}

<div class="container-fluid text-center m-auto">
    <h1 class="h1 border p-3 mb-5 mt-3">{% if form.instance.pk %}تعديل{% else %} انشاء {% endif %} سجل تحصيل  {{cloth.name}}</h1>
    <div class="row">
        <div class="col-4 mb-5 border border-danger p-4">
            <form method="post">
                    {% csrf_token %}
                    {{ form | crispy}}
                <button type="submit" class="btn btn-danger text-white d-block w-100 h3 mt-3">حفظ</button>
            </form>
        </div>
        <div class="col-7 border p-3">
            <div class="row selectAllToggle mb-5">
                <div class="col-6">
                    <button class="btn btn-primary w-100 chosen-toggle select-all">تحديد الكل</button>
                </div>
                <div class="col-4 mr-auto">
                    <button class="btn btn-info text-white w-100 chosen-toggle deselect-all">الغاء تحديد الكل</button>
                </div>
            </div>
            <h2>سجل التحصيلات</h2>
            <table class="table-bordered text-center w-100 h6">
                <thead>
                    <tr>
                        <th>اسم التحصيل</th>
                        <th>المحصل</th>
                        <th>سريال الدفتر</th>
                        <th>تاريخ اصدار التحصيل</th>
                    </tr>
                </thead>
                <tbody>
                        <tr>
                            <td>2</td>
                            <td>3</td>
                            <td>4</td>
                            <td>4</td>
                        </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
        $("#id_clientt").chosen({rtl: true, height:'10rem'});

        $('#id_clientt_chosen ul.chosen-choices').css({
            height      :   "10rem",
            overflow    :   "scroll"
        });

        

        $('.select-all').click(function() {
            $("#id_clientt option").prop("selected", true);
            // Trigger Chosen update only once after all changes
            $('#id_clientt').trigger('chosen:updated');
        });

        $("#id_clientt option").prop("selected", true);
            // Trigger Chosen update only once after all changes
            $('#id_clientt').trigger('chosen:updated');
        
        $('.deselect-all').click(function() {
            $("#id_clientt option").prop("selected", false);
            // Trigger Chosen update only once after all changes
            $('#id_clientt').trigger('chosen:updated');
        });
{% endblock %}

collect/templates/collect/follow_list.html
{% extends "collect/index.html" %}    
{% load static %}

{% block title %}
    <title>سجل متابعة تعاقد العملاء</title>
{% endblock %}

{% block style %}
    <!-- Your styles go here -->
{% endblock %}

{% block content %}
<div class="container-fluid">
    
    <div class="row">
        <div class="col-10 m-auto">
            <form method="get">
                <div class="input-group mb-3">
                    <input type="text" name="search" class="form-control" placeholder="ابحث بالاسم او السريال او المنطقة" aria-label="Recipient's Name" aria-describedby="button-addon2">
                    <button class="btn btn-primary" type="submit">ابحث</button>
                </div>
            </form>
            <p class="bg-light text-right d-inline-block p-3 m-1 h6">
                عدد العملاء : <span class="text-primary">{{total_count}}</span>
            </p>
            <button class="btn btn-danger w-50 h3"  data-toggle="modal" data-target="#newCollectOrderModel" style="margin-right:10rem">انشاء طلب تحصيل</button>    
            
        </div>
        <div class="modal fade" id="newCollectOrderModel" tabindex="-1" role="dialog" aria-labelledby="newCollectOrderModelTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">تفاصيل طلب التحصيل</h5>
                        <button type="button" class="close" data-dismiss="modal" id="modal_close" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                        <p class="btn btn-danger" id="success_new_request"></p>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label>اختار المحصل</label>
                            <select class="select form-control" name="collector" id="collector">
                                {% for collector in collectors %}
                                <option value="{{collector.id}}">{{collector.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label>تاريخ بدء التحصيل</label>
                            <input type="date" class="form-control" name="collectStartDate" id="collectStartDate">
                        </div>
                        <div class="form-group">
                            <label>سريال دفتر التحصيل</label>
                            <input type="" class="form-control" name="serial" id="serial">
                        </div>
                        

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary ml-2 collect-btn">تأكيد وحفظ</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">الغاء</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3 mr-auto h3 ">
            <a class="btn btn-warning w-100 p-2 h3" onclick="cancelCheckAll()">الغاء تحديد الكل</a>
            <a class="btn btn-success w-100 p-2 text-white" onclick="checkAll()">تحديد الكل</a>
        </div>
        <div class="col-10"  style="position: fixed; top: 16rem; display: inline-block; left: 0rem; z-index:2; overflow:scroll; height:67vh">
            <table class="table table-bordered table-sm text-center table-hover table-striped" >
                <thead>
                    <tr>
                        <th>السريال</th>
                        <th>الاسم</th>
                        <th>المنطقة</th>
                        <th>المزيد</th>
                        <th>تاريخ التحصيل التالى</th>
                        <th>اضافة لطلب التحصيل</th>

                    </tr>
                </thead>
                <tbody>
                    {% for follow in follows %}
                        <tr>
                            <td>{{ follow.clientt.serial }}</td>
                            <td>{{ follow.clientt.name }}</td>
                            <td>{{ follow.clientt.place.name }}</td>
                            <td>
                                <a class="btn btn-info" href="#">المزيد / اوامر اضافية</a>
                            </td>
                            <td>
                                {{follow.ecd|date:"Y-m-d"}}
                            </td>

                            <td>
                                <input type="checkbox" class="client-checkbox form-control" style=" height: 2rem; " checked value="{{follow.id}}">
                                <input type="hidden" value={{follow.clientt.id}}>
                            </td>
                        </tr>

                    {% empty %}
                        <li>No client found.</li>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<input type="hidden" value="{{csrf_token}}" id="csrf_token">
{% endblock %}

{% block script %}
    //check all


    function checkAll() {
        console.log("Started");
        $('.client-checkbox').prop('checked', true); // Check all
    }

    // cancel check all
    function cancelCheckAll() {
        console.log("Started");
        $('.client-checkbox').prop('checked', false); // Check all
    }

    // Collect selected clients and send to backend
    $('.collect-btn').click(function() {
        var collector           = $("#collector").val(),
            startCollectDate    = $("#collectStartDate").val(),
            serial              = $("#serial").val(),
            selectedClients     = [];
        $('.client-checkbox:checked').each(function() {
            selectedClients.push($(this).next().val());
        });
        console.log("selectedClients=> ", selectedClients)

        // Send selected clients to backend using API
        $.ajax({
            url: '/collect/api/new_colect_order/',
            method: 'POST',
            data: JSON.stringify({
                'clients'           :   selectedClients,
                'serial'            :   serial,
                'startCollectDate'  :   startCollectDate,
                'collectorId'       :   collector,
                'csrfmiddlewaretoken':   $("#csrf_token").val(),
            }),
            success: function(response) {
                $("#success_new_request").text("تم انشاء طلب التحصيل بنجاح إغلق النافذة")
                alert('تم انشاء طلب التحصيل بنجاح إغلق النافذة');
                
            },
            error: function(error) {
                $("#success_new_request").text("حدثت مشكلة الرجاء التواصل مع المسؤول")
            }
        });
    });

    
{% endblock %}

collect/templates/collect/index.html
<!DOCTYPE html>
<html lang="ar">
<head>
	<!-- Add additional CSS in static file -->
  {% load static %}
  {{ form.media }}
  {% block title %}{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'cAccounts/css/bootstrap.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'cAccounts/css/chosen.min.css' %}" />
  <link rel="stylesheet" href="{% static 'cAccounts/css/chosen-sprite.png' %}" />
  <link rel="stylesheet" href="{% static 'cAccounts/css/style.css' %}" />
  <script src="{% static 'cAccounts/js/jquery.min.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}">
  <style>
    .btn-custom{
      /*background-color:#6c757d00 !important;*/
      /*border:none;*/
    }
  {% block style %}
  {% endblock %}
  </style>
</head>
{% load bootstrap4 %}
{% load crispy_forms_tags %}
<body>
	<div class="container-fluid text-right" dir="rtl">
	    <div class="row">
	        <div class="col-12">
	            <div class="float-right">
	                {% comment %} <img class="w-100" src="https://drive.google.com/uc?id=1ocKY9NAlM4rVEtlr7D8OaJN3s48UbiNe" > {% endcomment %}
	            </div>
	            <div class="float-left">
	                <div class="dropdown">
                        <button class="btn dropdown-toggle" style="" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user-circle fa-2x text-danger" aria-hidden="true"></i>
                        </button>
                        <div class="dropdown-menu bg-dark text-right text-white" aria-labelledby="dropdownMenuButton">
                            <h5 class="bg-primary text-white">مرحبا {{request.user.get_short_name}}</h5>
                            <a class="dropdown-item text-white" href="#">الملف الشخصى</a>
                            <a class="dropdown-item text-white" href="#">الاشعارات</a>
                            <a class="dropdown-item text-white" href="/cAccounts/logout">تسجيل الخروج</a>
                        </div>
                    </div>
	            </div>
	        </div>
	    </div>
    	<div class="row" style="height:89vh">
    	    <div class="col-2 pt-5 text-white" style="background-color:#30393D">
                <a href="#" class="">
                    <button class="btn btn-secondary w-100 m-2  btn-custom">ملخص / نبذه</button>
                </a>
                <a href="" class="">    
                    <button class="btn btn-secondary w-100 m-2  btn-custom">سجل تحصيل العملاء</button>
                </a>
                <a href="{% url 'collect:list' %}" class="">
                    <button class="btn btn-secondary w-100 m-2  btn-custom" >انشاء طلب تحصيل جديد</button>
                </a>
                <a href="#" class="">
                    <button class="btn btn-secondary w-100 m-2  btn-custom">ادارة تحصيل العملاء</button>
                </a>
                <a href="{% url 'collect:request_list' %}" class="">
                    <button class="btn btn-secondary w-100 m-2  btn-custom">متابعة طلبات التحصيل الجارية</button>
                </a>
                <a href="#" class="">
                    <button class="btn btn-secondary w-100 m-2  btn-custom">سجل المحصلين</button>
                </a>
                <a href="#" class="">
                    <button class="btn btn-secondary w-100 m-2  btn-custom">ما تم تحصيله</button>
                </a>
    	    </div>
    	    <div class="col-10">
                {% block content %}{% endblock %}
    	    </div>
    	</div>

	</div>

    <script src="{% static 'cAccounts/js/jquery.min.js' %}"></script>
    <script src="{% static 'cAccounts/js/popper.min.js' %}"></script>
    <script src="{% static 'cAccounts/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'cAccounts/js/htmx.js' %}"></script>
    <script src="{% static 'cAccounts/js/chosen.js'%}"></script>
    <script>
        {% block script %}
        {% endblock %}
    </script>

    <script>
</script>
</body>
</html>